export type PulseType = 'news' | 'linkedin' | 'press_release' | 'event' | 'budget';

export interface PulseItem {
  id: string;
  districtId: string;
  districtName: string;
  type: PulseType;
  headline: string;
  summary: string;
  source: string;
  date: string;
  reachOutHint: string;
  urgent?: boolean;
}

export const pulseItems: PulseItem[] = [
  {
    id: 'p1',
    districtId: 'oakwood',
    districtName: 'James Whitfield',
    type: 'budget',
    headline: 'James Whitfield\'s company approves $2.1M tech infrastructure budget for FY2026',
    summary: 'Board voted 6-1 to approve expanded technology spending, with specific line items for access management and safety systems.',
    source: 'Oakwood Tribune',
    date: '2025-11-18',
    reachOutHint: 'Budget approved — great time to push the outstanding proposal. James has the funds.',
    urgent: true,
  },
  {
    id: 'p2',
    districtId: 'willowbrook',
    districtName: 'Diana Calloway',
    type: 'news',
    headline: 'Diana Calloway\'s organization named Top 10 in regional safety audit',
    summary: 'The state recognized the organization for improvements in access protocols. Diana cited a need for "smarter systems at entry points."',
    source: 'Industry Wire',
    date: '2025-11-14',
    reachOutHint: 'They just won a safety award — perfect angle: "Congrats, our solution would complete the picture."',
    urgent: true,
  },
  {
    id: 'p3',
    districtId: 'lone-star',
    districtName: 'Carlos Vega',
    type: 'linkedin',
    headline: 'Carlos Vega posted: "Exploring modern access management systems for our organization"',
    summary: 'Decision maker publicly signaling interest in upgrading their infrastructure. Post has 47 likes from peers in the industry.',
    source: 'LinkedIn',
    date: '2025-11-20',
    reachOutHint: 'He\'s publicly shopping. Reply to the post + follow up on the proposal same day.',
    urgent: true,
  },
  {
    id: 'p4',
    districtId: 'foxhill',
    districtName: 'Gretchen Holt',
    type: 'event',
    headline: 'Gretchen Holt co-organizing regional tech showcase — Jan 14, 2026',
    summary: 'Gretchen is co-organizing a technology showcase. 12 companies attending.',
    source: 'Industry Newsletter',
    date: '2025-11-10',
    reachOutHint: 'Ask Gretchen if the platform can demo at the showcase. One event → 12 warm referrals.',
  },
  {
    id: 'p5',
    districtId: 'suncoast',
    districtName: 'Angela Moore',
    type: 'news',
    headline: 'New compliance regulation mandates digital tracking logs by March 2026',
    summary: 'New requirement covers all organizations in the sector. Manual processes will not meet the standard.',
    source: 'Regulatory Bulletin',
    date: '2025-11-08',
    reachOutHint: 'Compliance deadline creates urgency. Send Angela a one-liner: "March deadline — we can have you live in 3 weeks."',
    urgent: true,
  },
  {
    id: 'p6',
    districtId: 'bay-state',
    districtName: 'Richard Chen',
    type: 'linkedin',
    headline: 'Richard Chen shared article: "Why Organizations Need Smarter Management Systems"',
    summary: 'Richard actively engaging with relevant content. Has commented on 3 posts about operations management this month.',
    source: 'LinkedIn',
    date: '2025-11-17',
    reachOutHint: 'Warm lead becoming warmer. Follow up on the pilot — if it closes, it opens the door to a full engagement.',
  },
  {
    id: 'p7',
    districtId: 'elmwood',
    districtName: 'Rebecca Torres',
    type: 'news',
    headline: 'Rebecca Torres\'s organization restructured following leadership change',
    summary: 'Former director retired. New interim named this week. Decision-making authority may have shifted.',
    source: 'Industry Gazette',
    date: '2025-11-21',
    reachOutHint: 'Rebecca Torres may have new chain of command. Re-introduce the platform to the new contact before the proposal goes cold.',
    urgent: true,
  },
  {
    id: 'p8',
    districtId: 'sunrise-academy',
    districtName: 'Paul Decker',
    type: 'event',
    headline: 'Paul Decker\'s organization hosting open enrollment event — Dec 3',
    summary: 'Event expected to bring 200+ attendees. Paul Decker confirmed as lead for the event.',
    source: 'Organization Website',
    date: '2025-11-19',
    reachOutHint: 'Great timing — reach out and offer a bundle in time for new enrollment. Upsell from pilot to a larger engagement.',
  },
  {
    id: 'p9',
    districtId: 'oakwood',
    districtName: 'James Whitfield',
    type: 'linkedin',
    headline: 'James Whitfield connected with 3 competitors on LinkedIn',
    summary: 'Activity suggests James may be doing competitive research. Two of the profiles are sales reps from rival vendors.',
    source: 'LinkedIn',
    date: '2025-11-22',
    reachOutHint: 'Competitor activity detected. Call James this week — don\'t let the pending proposals go stale.',
    urgent: true,
  },
  {
    id: 'p10',
    districtId: 'suncoast',
    districtName: 'Angela Moore',
    type: 'press_release',
    headline: 'Angela Moore\'s organization named regional finalist for excellence award',
    summary: 'Recognition highlights operational improvements over the past 18 months.',
    source: 'Industry Association',
    date: '2025-11-05',
    reachOutHint: 'Congratulate Angela — "Organizations of the Year use tools that match their reputation. Let\'s close this out."',
  },
  {
    id: 'p11',
    districtId: 'foxhill',
    districtName: 'Gretchen Holt',
    type: 'budget',
    headline: 'Gretchen Holt\'s organization confirms $48K tech allocation for Q1',
    summary: 'Funding confirmed for infrastructure and connectivity improvements.',
    source: 'Internal Budget Report',
    date: '2025-11-16',
    reachOutHint: 'Funding unlocked. Relevant line items on the proposal are eligible — remind Gretchen.',
    urgent: true,
  },
  {
    id: 'p12',
    districtId: 'willowbrook',
    districtName: 'Diana Calloway',
    type: 'budget',
    headline: 'Diana Calloway\'s board meeting scheduled Dec 10 — procurement on agenda',
    summary: 'Agenda includes technology procurement approvals. Items under $50K can be approved at board level.',
    source: 'Organization Calendar',
    date: '2025-11-23',
    reachOutHint: 'Proposal is under the $50K threshold. Get Diana to add it to the Dec 10 agenda.',
    urgent: true,
  },
];

export const pulseTypeConfig: Record<PulseType, { label: string; color: string; bg: string }> = {
  news: { label: 'News', color: '#3b82f6', bg: 'rgba(59,130,246,0.1)' },
  linkedin: { label: 'LinkedIn', color: '#0ea5e9', bg: 'rgba(14,165,233,0.1)' },
  press_release: { label: 'Press Release', color: '#8b5cf6', bg: 'rgba(139,92,246,0.1)' },
  event: { label: 'Event', color: '#f59e0b', bg: 'rgba(245,158,11,0.1)' },
  budget: { label: 'Budget Signal', color: '#22c55e', bg: 'rgba(34,197,94,0.1)' },
};
